# Generated by Django 4.2.19 on 2025-02-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0002_gameweek_rename_position_player_element_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
